config/routes.rb
Rails.application.routes.draw do

  root 'main_page#index'

# ********************LOG IN************************************************
  get 'user_sessions/new'
  get 'user_sessions/create'
  get "/register" => "users#new", as: :register 
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
# **************************************************************************
 
# *******************RESOURCES********************************************** 
  resources :users
  resources :profile_pictures
  resources :artists
  resources :main_page, only: [:index]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :audios
# **************************************************************************





end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :user
	has_many :audios

# ************* cover photo *****************
	has_attached_file :cover_photo, styles:{
		medium: '300x300>'
	}

	validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true, length:(2..50), uniqueness: true
	validates :artist_type, presence: true
	validates :genre, presence: true, length:(2..50)
	validates :bio, presence: true




end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @current_user = User.find(session[:user_id]) if session[:user_id]
    @current_artist = Artist.find_by(user_id: @current_user)
    @audio = @current_artist.audios.all
  end

  # GET /artists/new
  def new
    @artist = current_user.artists.new
  end

  # GET /artists/1/edit
  def edit
    @current_user = User.find(session[:user_id]) if session[:user_id]
    @current_artist = Artist.find_by(user_id: @current_user)

  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = current_user.artists.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @current_user, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @current_user, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :artist_type, :genre, :bio, :user_id, :cover_photo, :id)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Artist Name' %>
    <%= f.input :artist_type, label: 'Type of Artist', collection: ['Individual','Band'], prompt: "Select One" %>
    <%= f.input :genre, label: 'Genre' %>
    <%= f.input :bio, label: 'Biography' %>

    <%= f.input :cover_photo, html: { class: 'form-control'}, label: "Add a cover photo" %> 
    <% if f.object.cover_photo? %>
      <br>
      <%= image_tag(f.object.cover_photo.url(:medium)) %>
      <br>
      <em>Current cover photo</em>
    <% end %>

  </div>

  <div class="form-actions form_sign_up ">
    <%= f.submit "Create Artist", class: "btn btn-success" %>
  </div>

  

<% end %>

app/views/artists/edit.html.erb
<%= link_to 'Back', artist_path(@current_artist) %>

<h1>Editing artist</h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<!-- A list of all the Artists -->
<h1>Listing artists</h1>


    <% @artists.each do |artist| %>
      <%= link_to artist_path(artist) do %> 
        <div class="artist_select">
        
          <%= artist.name %>

        </div>
    	<% end %>
    <% end %>


<br>

app/views/artists/new.html.erb
<h1>New Artist</h1>
<h4>By becoming an artist you are taking the first step to sharing your original music with the world.</h4>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/artists/show.html.erb
<!-- The artists main page -->

<!-- ******** Information that everyone can see/ access ******** -->
<h1><%= @artist.name %></h1>

<%= image_tag @artist.cover_photo.url(:medium) %>
<br>
<strong>Name: </strong><%= @artist.name %>
<br>
<strong>Type: </strong><%= @artist.artist_type %>
<br>
<strong>Genre: </strong><%= @artist.genre %>
<br>
<strong>Bio: </strong><%= safe_join(@artist.bio.split("\r\n"), "<br />".html_safe)%>
<br>



<!-- ******** Give the Artist owner more controll of the artist page. ******** -->

<% if @current_artist && @current_artist.id == @artist.id %>
	<%= link_to "Edit Information", edit_artist_path(@artist), class: "btn btn-xs btn-primary" %>

<br>
<br>
<div>
	<%= link_to "Add a Song", new_audio_path, class: "btn btn-success" %>
</div>
<!-- ************* Displays the songs an Artist uploaded **************************** -->
<h1>Your Music</h1>
	<% if @current_artist.audios.count == 0 %>
		<em>You have not uploaded any songs yet</em>
	<% else %>
		<%= render file: "app/views/audios/_songs" %>
	<% end %>
<!-- ******************************************************************************** -->
<% end %>

<!-- !!!!!! currently does not display artists songs on their page for other users to see. -->