config/routes.rb
Rails.application.routes.draw do

  root 'main_page#index'

# ********************LOG IN************************************************
  get 'user_sessions/new'
  get 'user_sessions/create'
  get "/register" => "users#new", as: :register 
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
# **************************************************************************
 
# *******************RESOURCES********************************************** 
  resources :users
  resources :profile_pictures
  resources :artists
  resources :main_page, only: [:index]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :audios
# **************************************************************************





end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

# *********** RELATIONSHIPS ************************
    has_many :profile_pictures
    has_many :artists
    
# *********** VALIDATIONS **************************
    validates :first_name, presence: true, length:(2..50)

    validates :last_name, presence: true, length:(2..50)

    validates :email, presence: true, 
                      uniqueness: true,
                      format: {
                        with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/
                      }
    validates :zip_code, presence: true, length: {is: 5}
    validates :terms_conditions, presence: true                 

# *********** Calls Functions ************************
    geocoded_by :zip_code
    after_validation :geocode, :if => :zip_code_changed?
    before_save :downcase_email
    before_save :capitalize_name

# *********  FUNCTIONS ******************************
 
    def full_name 
        self.first_name + " " + self.last_name
    end

    def downcase_email
        self.email = email.downcase
    end

    def capitalize_name
        self.first_name = first_name.capitalize
        self.last_name = last_name.capitalize
    end

    def generate_password_reset_token!
        update_attribute(:password_reset_token, SecureRandom.urlsafe_base64(48))
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def show
    @current_user = User.find(session[:user_id]) if session[:user_id]
    @current_artist = Artist.find_by(user_id: @current_user)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Thanks for signing up!"
        format.html { redirect_to user_path(@user)}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :zip_code, :latitude, :longitude, :terms_conditions)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, label: 'First Name' %>
    <%= f.input :last_name, label: 'Last Name' %>
    <%= f.input :email, label: 'Email' %>
    <%= f.input :password, label: 'Password' %>
    <%= f.input :password_confirmation, label: 'Password Confirmation'%>

    <%= f.input :zip_code, label: 'Zip Code' %>
    <%= f.input :terms_conditions, label: 'I agree to the terms and conditions' %>

  </div>

  <div class="form-actions form_sign_up ">
    <%= f.submit "Submit", class: "btn btn-success" %>
  </div>

  

<% end %>

app/views/users/edit.html.erb
<%= link_to 'Back', @user %>

<h1>Edit Your Information</h1>

<%= render :file => "app/views/profile_pictures/_edit_options" %>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>
<%= link_to 'Log In', login_path  %>

app/views/users/show.html.erb
<!--  The profile page for individual users. -->
<% if @user == @current_user %>
	<h1>Hello, <%= @user.full_name %></h1>

	<%= link_to 'Edit Information', edit_user_path(@user), class: 'btn btn-xs btn-primary' %>

<!-- Profile Picture -->
	<%= render :file => "app/views/profile_pictures/_icon" %>

	<% if @current_user.profile_pictures.count == 0 %>
		<%= link_to 'Add Profile Picture', new_profile_picture_path(), class: 'btn btn-xs btn-primary' %>
	<% end %>

<!-- Creating an artist page -->
<% if @current_user.artists.count == 0 %>
	<h4>This is your personal profile page. To begin uploading originial music you must first bacome an artist.</h4>
	<%= link_to "Create New Artist", new_artist_path, class: 'btn btn-success' %>
<% else %>
	<h4>This is your personal profile page. To visit the page for <strong><%=@current_artist.name%></strong> click the link below. </h4>
	<%= link_to "View Artist Page", artist_path(@current_artist.id), class: 'btn btn-primary' %>
<% end %>




<!-- if the user id does not match the current user -->
<% else %>
	<%= render file: 'public/404', status: :not_found %> 
<% end %>