config/routes.rb
Rails.application.routes.draw do

  root 'main_page#index'

# ********************LOG IN************************************************
  get 'user_sessions/new'
  get 'user_sessions/create'
  get "/register" => "users#new", as: :register 
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
# **************************************************************************
 
# *******************RESOURCES********************************************** 
  resources :users
  resources :profile_pictures
  resources :artists
  resources :main_page, only: [:index]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :audios
# **************************************************************************





end

app/models/profile_picture.rb
class ProfilePicture < ActiveRecord::Base
	belongs_to :user

	has_attached_file :asset, 
	:styles =>{
		:round => '500x500>',
		:medium => '300x300>',
		:large_thumb => '140x140>',
		:thumb => '50x50#' 
	},
		:path => "profile_pictures/:id/:style.:extension", 
        :storage => :s3, 
        :bucket => "melodicisland",
        :s3_credentials => {
        	:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
        	}
	
	
	validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profile_pictures_controller.rb
class ProfilePicturesController < ApplicationController
  before_action :require_user
  before_action :set_profile_picture, only: [:show, :edit, :update, :destroy]

  # GET /profile_pictures
  # GET /profile_pictures.json
  def index
    @profile_pictures = current_user.profile_pictures
  end

  # GET /profile_pictures/1
  # GET /profile_pictures/1.json
  def show
  end

  # GET /profile_pictures/new
  def new
    @profile_picture = current_user.profile_pictures.new
  end

  # GET /profile_pictures/1/edit
  def edit
  end

  # POST /profile_pictures
  # POST /profile_pictures.json
  def create
    @profile_picture = current_user.profile_pictures.new(profile_picture_params)

    respond_to do |format|
      if @profile_picture.save
        format.html { redirect_to user_path(@current_user), notice: 'Profile picture was successfully created.' }
        format.json { render :show, status: :created, location: @profile_picture }
      else
        format.html { render :new }
        format.json { render json: @profile_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_pictures/1
  # PATCH/PUT /profile_pictures/1.json
  def update
    respond_to do |format|
      if @profile_picture.update(profile_picture_params)
        format.html { redirect_to edit_user_path(@current_user), notice: 'Profile picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile_picture }
      else
        format.html { render :edit }
        format.json { render json: @profile_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_pictures/1
  # DELETE /profile_pictures/1.json
  def destroy
    @profile_picture.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_path(@current_user), notice: 'Profile picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_picture
      @profile_picture = current_user.profile_pictures.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_picture_params
      params.require(:profile_picture).permit(:asset)
    end
end

app/helpers/profile_pictures_helper.rb
module ProfilePicturesHelper
end

app/views/profile_pictures/_edit_options.html.erb
<% current_user ||= User.find(session[:user_id]) if session[:user_id] %>
<% @profile_picture = current_user.profile_pictures %>

    <% @profile_picture.each do |profile_picture| %>
    <div>
        <%= image_tag profile_picture.asset.url(:medium) %>
    
        <br>
        <%= link_to 'Edit', edit_profile_picture_path(profile_picture) %>
        <%= link_to 'Destroy', profile_picture, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  
  <% end %>

  <% if current_user.profile_pictures.count == 0 %>
		<%= link_to 'Add Profile Picture', new_profile_picture_path(), class: 'btn btn-xs btn-primary' %>
  <% end %>

app/views/profile_pictures/_form.html.erb
<%= simple_form_for(@profile_picture, html: {multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	
  	<%= f.input :asset, html: { class: 'form-control'}, label: "Upload a profile picture" %> 
  	<% if f.object.asset? %>
  		<br>
  		<%= image_tag(f.object.asset.url(:round), class: "large_thumb") %>
      <br>
  		<em>Currently uploaded profile picture</em>
  	<% end %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/profile_pictures/_icon.html.erb
<% current_user ||= User.find(session[:user_id]) if session[:user_id] %>
<% @profile_picture = current_user.profile_pictures %>
	
    <% @profile_picture.each do |profile_picture| %>
		<div>
	    	<%= image_tag profile_picture.asset.url(:round), class: "thumb" %>
		</div>
    <% end %>

app/views/profile_pictures/crop.html.erb
<% content_for (:head) do %>
      <%= stylesheet_link_tag "jquery.Jcrop.min" %>
      <%= javascript_include_tag "jquery.Jcrop.min" %>
<% end %>
<%= form_for @profile_picture do |f| %>
  <%= f.cropbox :asset, :width => 500 %>
  <%= f.crop_preview :asset, :width => 150 %>
  <%= f.submit 'Save' %>
<% end %>

app/views/profile_pictures/edit.html.erb
<h1>Edit your Profile Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/profile_pictures/new.html.erb
<h1>Add a Profile Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>