config/routes.rb
Rails.application.routes.draw do

  root 'main_page#index'

# ********************LOG IN************************************************
  get 'user_sessions/new'
  get 'user_sessions/create'
  get "/register" => "users#new", as: :register 
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
# **************************************************************************
 
# *******************RESOURCES********************************************** 
  resources :users
  resources :profile_pictures
  resources :artists
  resources :main_page, only: [:index]
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :audios
# **************************************************************************





end

app/views/layouts/_footer.html.erb
</div> <!-- ends the div 'container'-->

<div class="footer">
	<p class = "copyright_date">&copy; <%= Date.today.year %> Melodic Island. All Rights Reserved</p>
</div>

app/views/layouts/_header.html.erb
<% @current_user = User.find(session[:user_id]) if session[:user_id] %>
<% @current_artist = Artist.find_by(user_id: @current_user) %>
<%= link_to main_page_index_path do%>
	<div class="header">
		<h1>Melodic Island</h1>
	</div>
<% end %>

<div class="log_in_out">

<!-- links that will be available to all users (with or with-out account) -->
		<li><%= link_to "Explore Artists", artists_path, class: 'btn btn-info' %></li>

	<% if @current_user%>
<!-- links that are only availabe to users who are signed in -->
		<% if @current_user.artists.count > 0 %>
			<li><%= link_to "Your Artist Page", artist_path(@current_artist.id), class: 'btn btn-primary' %></li>
		<% end %>
		<li><%= link_to "Songs", audios_path, class: 'btn btn-warning' %></li>
		<li><%= render :file => "app/views/profile_pictures/_icon" %></li>
		<li><%= link_to @current_user.full_name, user_path(@current_user) %></li>
		<li><%= link_to "Log Out", logout_path, method: :delete, class: 'btn btn-primary' %></li>	
	<% else %>
<!-- links only available to users who are not signed in -->
		<li><%= link_to "Sign Up", register_path, class: 'btn btn-primary' %></li>
		<li><%= link_to "Log In", login_path, class: 'btn btn-primary' %></li>
	<% end %>

</div>

<div class="container">

app/views/layouts/_notices.html.erb
<div>
	<% if flash[:notice] %>
		<div class="alert bg-success">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% end %>

	<% if flash[:alert] %>
		<div class="alert bg-danger">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>

	<% if flash[:error] %>
		<div class="alert bg-danger">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:error] %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Melodic Island</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/notices' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>